name: Publish

on: workflow_dispatch

permissions:
  id-token: write  # Required for OIDC
  contents: read
  
jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@kie'
          package-manager-cache: false  # never use caching in release builds
      
      - name: Install packages
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
